apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: task
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: tasks-api
          image: nikhilchandan/kub-dep-tasks
          env:
            - name: MONGODB_CONNECTION_URI
              # Replace the missing password and dbname in a real deployment
              value: 'mongodb+srv://nikhil:nikhil@cluster0.n6xcl.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
            - name: AUTH_API_ADDRESS
              value: 'auth-service.default:3000'
